baseURL = "http://rizwaniqbal.com/"
languageCode = "en-us"
title = "Rizwan Iqbal"
theme = "hermit"

[author]
  name = "Rizwan Iqbal"

[params]
  themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Personal Website"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rizwaniqbal"

  [[params.social]]
    name = "codepen"
    url = "https://codepen.io/rizwaniqbal"

  [[params.social]]
    name = "github"
    url = "https://github.com/rizwaniqbal"