baseURL = "https://rizwaniqbal.com/"
title = "Rizwan Iqbal"
theme = "hermit"
enableGitInfo = true
languageCode = "en-gb"
defaultContentLanguage = "en"
assetDir="assets"

[author]
  name = "Rizwan Iqbal"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "Jan 2 15:04:05 2006 MST"

  themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "An engineer intent on improving organisation culture"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rizwaniqbal"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rizwaniq/"

  [[params.social]]
    name = "github"
    url = "https://github.com/automaticalldramatic"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20
