baseURL = "http://rizwaniqbal.com/"
languageCode = "en-gb"
title = "Rizwan Iqbal"
theme = "hermit"

[author]
  name = "Rizwan Iqbal"

[params]
  themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Engineer based in Berlin"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rizwaniqbal"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rizwaniq/"

  [[params.social]]
    name = "github"
    url = "https://github.com/automaticalldramatic"
