title = "Rizwan Iqbal"
baseURL = "https://rizwaniqbal.com/"
theme = "hermit"
enableGitInfo = true
assetDir="assets"

# Updated configuration for newer Hugo versions
[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "Jan 2 15:04:05 2006 MST"

  themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Engineering leader passionate about building impactful developer experiences"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rizwaniqbal"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rizwaniq/"

  [[params.social]]
    name = "github"
    url = "https://github.com/automaticalldramatic"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1156254/automaticalldramatic"

  author = "Rizwan Iqbal"  # Moving author to params
  disqusShortname = "automaticalldramatic"  # Moving Disqus to params
  googleAnalytics = "UA-171167229-1"  # Moving GA to params

  comments = true  # Enable comments globally
  # Show comment count on post summaries
  showComments = true

[services]
  [services.googleAnalytics]
    ID = "UA-171167229-1"

[pagination]
  pagerSize = 10  # Replaces old paginate parameter

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      subtitle = "An engineer intent on busting the myth of developer productivity"
