baseURL = "https://rizwaniqbal.com/"
title = "Rizwan Iqbal"
theme = "hermit"
enableGitInfo = true
languageCode = "en-gb"
defaultContentLanguage = "en"

[author]
  name = "Rizwan Iqbal"

[params]
  dateform        = "Jun 5, 2019"
  dateformShort   = "Jun 5"
  dateformNum     = "2019-06-05"
  dateformNumTime = "2019-06-05 15:04 +0530"

  themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "Engineer based in Berlin"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/rizwaniqbal"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/rizwaniq/"

  [[params.social]]
    name = "github"
    url = "https://github.com/automaticalldramatic"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20
